; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-core-esp32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = m5stack-core-esp32
framework = arduino
board_build.partitions = max_app_4MB.csv
monitor_speed = 115200
lib_deps =
    m5stack/M5Unified
build_flags =
    -DCORE_DEBUG_LEVEL=3
